name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::585768185698:role/githubActionsRole
          aws-region: us-west-1

      - name: Build Static Site
        run: npm ci && npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://codeelijahtext.com --delete
